[package]
name = "timely-coherent-logic"
version = "0.1.0"
authors = ["Paul Khuong <pvk@pvk.ca>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
